# Copyright 2024 Collate
# Licensed under the Apache License, Version 2.0
"""Domain models for the DataPulse incident lifecycle."""

from __future__ import annotations

from datetime import datetime, timezone
from enum import IntEnum, StrEnum
from uuid import uuid4

from pydantic import BaseModel, Field


class Severity(IntEnum):
    """Incident severity levels (lower = more severe)."""

    CRITICAL = 1
    HIGH = 2
    MEDIUM = 3
    LOW = 4
    INFO = 5


class IncidentStatus(StrEnum):
    """Lifecycle states of a DataPulse incident."""

    DETECTED = "detected"
    INVESTIGATING = "investigating"
    REPORTED = "reported"
    ACKNOWLEDGED = "acknowledged"
    RESOLVED = "resolved"


class TestFailure(BaseModel):
    """A single data quality test failure detected by the Sentinel."""

    test_case_id: str
    test_case_name: str
    table_fqn: str
    column: str | None = None
    test_definition: str
    result_message: str
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class AffectedAsset(BaseModel):
    """An entity in the blast radius of an incident."""

    fqn: str
    entity_type: str
    display_name: str | None = None
    owners: list[str] = Field(default_factory=list)
    depth: int = 0  # hops from the root cause


class BlastRadius(BaseModel):
    """The upstream root-cause chain and downstream impact zone."""

    root_cause_table: str
    root_cause_column: str | None = None
    upstream_chain: list[AffectedAsset] = Field(default_factory=list)
    downstream_impact: list[AffectedAsset] = Field(default_factory=list)
    total_affected_assets: int = 0
    affected_owners: list[str] = Field(default_factory=list)


class IncidentReport(BaseModel):
    """Human-readable incident report generated by the Narrator."""

    summary: str
    root_cause_analysis: str
    blast_radius_description: str
    severity_justification: str
    recommendations: list[str] = Field(default_factory=list)
    generated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class Incident(BaseModel):
    """A DataPulse incident — the central entity of the system."""

    id: str = Field(default_factory=lambda: uuid4().hex[:12])
    title: str
    severity: Severity = Severity.MEDIUM
    status: IncidentStatus = IncidentStatus.DETECTED
    failures: list[TestFailure] = Field(default_factory=list)
    blast_radius: BlastRadius | None = None
    report: IncidentReport | None = None
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    updated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    def escalate(self, severity: Severity) -> None:
        self.severity = severity
        self.updated_at = datetime.now(timezone.utc)

    def transition(self, status: IncidentStatus) -> None:
        self.status = status
        self.updated_at = datetime.now(timezone.utc)
