# Copyright 2024 Collate
# Licensed under the Apache License, Version 2.0
"""Domain models for the DataPulse incident lifecycle."""

from __future__ import annotations

import sys
from datetime import datetime, timezone
from enum import IntEnum
from typing import List, Optional
from uuid import uuid4

from pydantic import BaseModel, Field

if sys.version_info >= (3, 11):
    from enum import StrEnum
else:
    from enum import Enum

    class StrEnum(str, Enum):
        """Backport of StrEnum for Python <3.11."""


class Severity(IntEnum):
    """Incident severity levels (lower = more severe)."""

    CRITICAL = 1
    HIGH = 2
    MEDIUM = 3
    LOW = 4
    INFO = 5


class IncidentStatus(StrEnum):
    """Lifecycle states of a DataPulse incident."""

    DETECTED = "detected"
    INVESTIGATING = "investigating"
    REPORTED = "reported"
    ACKNOWLEDGED = "acknowledged"
    RESOLVED = "resolved"


class FaultyRow(BaseModel):
    """A single row from the database that failed a DQ check."""

    row_data: dict
    reason: str = ""


class TestFailure(BaseModel):
    """A single data quality test failure detected by the Sentinel."""

    test_case_id: str
    test_case_name: str
    table_fqn: str
    column: Optional[str] = None
    test_definition: str
    result_message: str
    faulty_rows: List[FaultyRow] = Field(default_factory=list)
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class TestResultRecord(BaseModel):
    """A single historical test result for trend analysis."""

    timestamp: datetime
    status: str  # "Success" or "Failed"
    result_message: str = ""


class TestHistory(BaseModel):
    """Historical test results for a test case."""

    test_case_name: str
    results: List[TestResultRecord] = Field(default_factory=list)
    total_runs: int = 0
    failure_count: int = 0
    first_failure: Optional[datetime] = None
    is_recurring: bool = False


class AffectedAsset(BaseModel):
    """An entity in the blast radius of an incident."""

    fqn: str
    entity_type: str
    display_name: Optional[str] = None
    description: Optional[str] = None
    owners: List[str] = Field(default_factory=list)
    tier: Optional[str] = None
    domain: Optional[str] = None
    tags: List[str] = Field(default_factory=list)
    depth: int = 0  # hops from the root cause


class BlastRadius(BaseModel):
    """The upstream root-cause chain and downstream impact zone."""

    root_cause_table: str
    root_cause_column: Optional[str] = None
    upstream_chain: List[AffectedAsset] = Field(default_factory=list)
    downstream_impact: List[AffectedAsset] = Field(default_factory=list)
    total_affected_assets: int = 0
    affected_owners: List[str] = Field(default_factory=list)


class IncidentReport(BaseModel):
    """Human-readable incident report generated by the Narrator."""

    summary: str
    root_cause_analysis: str
    blast_radius_description: str
    severity_justification: str
    recommendations: List[str] = Field(default_factory=list)
    stakeholders_affected: str = ""
    trend_analysis: str = ""
    generated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class Incident(BaseModel):
    """A DataPulse incident — the central entity of the system."""

    id: str = Field(default_factory=lambda: uuid4().hex[:12])
    title: str
    severity: Severity = Severity.MEDIUM
    status: IncidentStatus = IncidentStatus.DETECTED
    failures: List[TestFailure] = Field(default_factory=list)
    failure_histories: List[TestHistory] = Field(default_factory=list)
    blast_radius: Optional[BlastRadius] = None
    report: Optional[IncidentReport] = None
    assigned_to: Optional[str] = None
    acknowledged_by: Optional[str] = None
    resolved_by: Optional[str] = None
    resolution_note: Optional[str] = None
    acknowledged_at: Optional[datetime] = None
    resolved_at: Optional[datetime] = None
    slack_thread_ts: Optional[str] = None
    slack_thread_url: Optional[str] = None
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    updated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    def escalate(self, severity: Severity) -> None:
        self.severity = severity
        self.updated_at = datetime.now(timezone.utc)

    def transition(self, status: IncidentStatus) -> None:
        VALID_TRANSITIONS = {
            IncidentStatus.DETECTED: {IncidentStatus.INVESTIGATING},
            IncidentStatus.INVESTIGATING: {IncidentStatus.REPORTED},
            IncidentStatus.REPORTED: {IncidentStatus.ACKNOWLEDGED, IncidentStatus.RESOLVED},
            IncidentStatus.ACKNOWLEDGED: {IncidentStatus.RESOLVED},
        }
        valid = VALID_TRANSITIONS.get(self.status, set())
        if status not in valid:
            # Allow no-op transitions (idempotent)
            if status == self.status:
                return
            raise ValueError(
                f"Cannot transition from {self.status.value} to {status.value}"
            )
        self.status = status
        self.updated_at = datetime.now(timezone.utc)
